[package]
name = "enigo"
version = "0.1.2"
authors = ["Dustin Bensing <dustin.bensing@googlemail.com>"]
edition = "2021"
build = "build.rs"
rust-version = "1.64"

description = "Enigo lets you control your mouse and keyboard in an abstract way on different operating systems (currently only Linux, macOS, Win – Redox and *BSD planned)"
documentation = "https://docs.rs/enigo/"
homepage = "https://github.com/enigo-rs/enigo"
repository = "https://github.com/enigo-rs/enigo"
readme = "README.md"
keywords = ["input", "mouse", "testing", "keyboard", "automation"]
categories = ["development-tools::testing", "api-bindings", "hardware-support"]
license = "MIT"

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[dev-dependencies]
tungstenite = "0.19"
url = "2.3"
webbrowser = "0.8"

[features]
with_serde = ["serde", "serde_derive"]
wayland = [
    "wayland-client",
    "wayland-protocols-misc",
    "wayland-protocols-wlr",
    "wayland-protocols-plasma",
    "memmap2",
    "tempfile",
]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
] }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = { version = "0.22", features = ["highsierra"] }
objc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
wayland-protocols-misc = { version = "0.1", features = [
    "client",
], optional = true }
wayland-protocols-wlr = { version = "0.1.0", features = [
    "client",
], optional = true }
wayland-protocols-plasma = { version = "0.1.0", features = [
    "client",
], optional = true }
wayland-client = { version = "0.30", optional = true }
x11rb = { version = "0.12", features = [
    "randr",
    "xinput",
    "xtest",
], optional = true }
xkbcommon = "0.6"
memmap2 = { version = "0.5", optional = true }
tempfile = { version = "3.5", optional = true }

[build-dependencies]
pkg-config = "0.3"
