name: "Install_deps"
description: "Installs the dependencies and updates the system"

runs:
  using: "composite"
  steps:
    - name:  Install dependencies
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update -q -y && sudo apt-get upgrade -y
          sudo apt-get install -y libxdo-dev libxkbcommon-dev libxi-dev libxtst-dev
          sudo apt-get install -y gettext imagemagick
          sudo apt-get install -y xdg-desktop-portal xdg-desktop-portal-gnome
          systemctl --user start xdg-desktop-portal
          systemctl --user start xdg-desktop-portal-gnome
          dbus-send --session --dest=org.freedesktop.portal.Desktop --type=method_call --print-reply / org.freedesktop.DBus.Introspectable.Introspect

         # sudo dnf upgrade -y --refresh
         # sudo dnf install -y gcc make automake autoconf libtool
         # sudo dnf install -y xdotool libxkbcommon-devel libXi-devel libXtst-devel ImageMagick
         # echo "$RUNNER_OS"
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo "$RUNNER_OS"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "$RUNNER_OS"
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
