name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update system
      run: sudo apt-get update -q -y && sudo apt-get upgrade -y
    - name: Install libxdo-dev
      run: sudo apt-get install -y libxdo-dev 
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose