name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "trace"

jobs:
  buid-test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}

    steps:
      - name:  Install dependencies
        run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update -q -y && sudo apt-get upgrade -y && sudo apt-get install -y libxdo-dev 
         elif [ "$RUNNER_OS" == "Windows" ]; then
         elif [ "$RUNNER_OS" == "macOS" ]; then
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
        shell: bash

      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build & Test (Default)
        run: cargo test --verbose
      - name: Build & Test (All features)
        run: cargo test --verbose --all-features