name: examples

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  examples:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - "1.31.0"
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_deps
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --examples

  examples_all_features:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - "1.31.0"
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_deps
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --examples --all-features
